/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'TokenTransferredMsg'
 * message type.
 */

public class TokenTransferredMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 7;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 13;

    /** Create a new TokenTransferredMsg of size 7. */
    public TokenTransferredMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new TokenTransferredMsg of the given data_length. */
    public TokenTransferredMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TokenTransferredMsg with the given data_length
     * and base offset.
     */
    public TokenTransferredMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TokenTransferredMsg using the given byte array
     * as backing store.
     */
    public TokenTransferredMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TokenTransferredMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public TokenTransferredMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TokenTransferredMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public TokenTransferredMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TokenTransferredMsg embedded in the given message
     * at the given base offset.
     */
    public TokenTransferredMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TokenTransferredMsg embedded in the given message
     * at the given base offset and length.
     */
    public TokenTransferredMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <TokenTransferredMsg> \n";
      try {
        s += "  [cmd=0x"+Long.toHexString(get_cmd())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [tokenId=0x"+Long.toHexString(get_tokenId())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [destinationId=0x"+Long.toHexString(get_destinationId())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [temperature=0x"+Long.toHexString(get_temperature())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: cmd
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'cmd' is signed (false).
     */
    public static boolean isSigned_cmd() {
        return false;
    }

    /**
     * Return whether the field 'cmd' is an array (false).
     */
    public static boolean isArray_cmd() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'cmd'
     */
    public static int offset_cmd() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'cmd'
     */
    public static int offsetBits_cmd() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'cmd'
     */
    public short get_cmd() {
        return (short)getUIntBEElement(offsetBits_cmd(), 8);
    }

    /**
     * Set the value of the field 'cmd'
     */
    public void set_cmd(short value) {
        setUIntBEElement(offsetBits_cmd(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'cmd'
     */
    public static int size_cmd() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'cmd'
     */
    public static int sizeBits_cmd() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: tokenId
    //   Field type: int, unsigned
    //   Offset (bits): 8
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'tokenId' is signed (false).
     */
    public static boolean isSigned_tokenId() {
        return false;
    }

    /**
     * Return whether the field 'tokenId' is an array (false).
     */
    public static boolean isArray_tokenId() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'tokenId'
     */
    public static int offset_tokenId() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'tokenId'
     */
    public static int offsetBits_tokenId() {
        return 8;
    }

    /**
     * Return the value (as a int) of the field 'tokenId'
     */
    public int get_tokenId() {
        return (int)getUIntBEElement(offsetBits_tokenId(), 16);
    }

    /**
     * Set the value of the field 'tokenId'
     */
    public void set_tokenId(int value) {
        setUIntBEElement(offsetBits_tokenId(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'tokenId'
     */
    public static int size_tokenId() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'tokenId'
     */
    public static int sizeBits_tokenId() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: destinationId
    //   Field type: int, unsigned
    //   Offset (bits): 24
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'destinationId' is signed (false).
     */
    public static boolean isSigned_destinationId() {
        return false;
    }

    /**
     * Return whether the field 'destinationId' is an array (false).
     */
    public static boolean isArray_destinationId() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'destinationId'
     */
    public static int offset_destinationId() {
        return (24 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'destinationId'
     */
    public static int offsetBits_destinationId() {
        return 24;
    }

    /**
     * Return the value (as a int) of the field 'destinationId'
     */
    public int get_destinationId() {
        return (int)getUIntBEElement(offsetBits_destinationId(), 16);
    }

    /**
     * Set the value of the field 'destinationId'
     */
    public void set_destinationId(int value) {
        setUIntBEElement(offsetBits_destinationId(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'destinationId'
     */
    public static int size_destinationId() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'destinationId'
     */
    public static int sizeBits_destinationId() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: temperature
    //   Field type: int, unsigned
    //   Offset (bits): 40
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'temperature' is signed (false).
     */
    public static boolean isSigned_temperature() {
        return false;
    }

    /**
     * Return whether the field 'temperature' is an array (false).
     */
    public static boolean isArray_temperature() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'temperature'
     */
    public static int offset_temperature() {
        return (40 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'temperature'
     */
    public static int offsetBits_temperature() {
        return 40;
    }

    /**
     * Return the value (as a int) of the field 'temperature'
     */
    public int get_temperature() {
        return (int)getUIntBEElement(offsetBits_temperature(), 16);
    }

    /**
     * Set the value of the field 'temperature'
     */
    public void set_temperature(int value) {
        setUIntBEElement(offsetBits_temperature(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'temperature'
     */
    public static int size_temperature() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'temperature'
     */
    public static int sizeBits_temperature() {
        return 16;
    }

}
