COMPONENT=TestGtsAppC
CFLAGS += -I$(TOSDIR)/lib/printf
PFLAGS += -DIEEE154_BEACON_TX_DISABLED 
CFLAGS += -I$(shell pwd)/..
#PFLAGS += -DPRINTF_BUFFER_SIZE=512

include $(TOSCONTRIB)/kth/tkn154-gts/apps/Makefile.include

#include ../../../Makefile.include
