COMPONENT=SensorAppC
	CFLAGS += -I$(shell pwd)/..
	CFLAGS += -I$(TOSDIR)/lib/printf
# some debugs (you problably also want this, although it's not required).
CFLAGS += -DPRINTFUART_ENABLED 
PFLAGS += -DIEEE154_BEACON_TX_DISABLED
		  

include ../Makefile.include
