/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'ActuationMatrixMsg'
 * message type.
 */

public class ActuationMatrixMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 16;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 11;

    /** Create a new ActuationMatrixMsg of size 16. */
    public ActuationMatrixMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new ActuationMatrixMsg of the given data_length. */
    public ActuationMatrixMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ActuationMatrixMsg with the given data_length
     * and base offset.
     */
    public ActuationMatrixMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ActuationMatrixMsg using the given byte array
     * as backing store.
     */
    public ActuationMatrixMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ActuationMatrixMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public ActuationMatrixMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ActuationMatrixMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public ActuationMatrixMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ActuationMatrixMsg embedded in the given message
     * at the given base offset.
     */
    public ActuationMatrixMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ActuationMatrixMsg embedded in the given message
     * at the given base offset and length.
     */
    public ActuationMatrixMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <ActuationMatrixMsg> \n";
      try {
        s += "  [u=";
        for (int i = 0; i < 8; i++) {
          s += "0x"+Long.toHexString(getElement_u(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: u
    //   Field type: short[], signed
    //   Offset (bits): 0
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'u' is signed (true).
     */
    public static boolean isSigned_u() {
        return true;
    }

    /**
     * Return whether the field 'u' is an array (true).
     */
    public static boolean isArray_u() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'u'
     */
    public static int offset_u(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 8) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'u'
     */
    public static int offsetBits_u(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 8) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'u' as a short[]
     */
    public short[] get_u() {
        short[] tmp = new short[8];
        for (int index0 = 0; index0 < numElements_u(0); index0++) {
            tmp[index0] = getElement_u(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'u' from the given short[]
     */
    public void set_u(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_u(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'u'
     */
    public short getElement_u(int index1) {
        return (short)getSIntBEElement(offsetBits_u(index1), 16);
    }

    /**
     * Set an element of the array 'u'
     */
    public void setElement_u(int index1, short value) {
        setSIntBEElement(offsetBits_u(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'u'
     */
    public static int totalSize_u() {
        return (128 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'u'
     */
    public static int totalSizeBits_u() {
        return 128;
    }

    /**
     * Return the size, in bytes, of each element of the array 'u'
     */
    public static int elementSize_u() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'u'
     */
    public static int elementSizeBits_u() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'u'
     */
    public static int numDimensions_u() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'u'
     */
    public static int numElements_u() {
        return 8;
    }

    /**
     * Return the number of elements in the array 'u'
     * for the given dimension.
     */
    public static int numElements_u(int dimension) {
      int array_dims[] = { 8,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
