/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'MyMsg'
 * message type.
 */

public class MyMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 24;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 10;

    /** Create a new MyMsg of size 24. */
    public MyMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new MyMsg of the given data_length. */
    public MyMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MyMsg with the given data_length
     * and base offset.
     */
    public MyMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MyMsg using the given byte array
     * as backing store.
     */
    public MyMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MyMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public MyMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MyMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public MyMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MyMsg embedded in the given message
     * at the given base offset.
     */
    public MyMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new MyMsg embedded in the given message
     * at the given base offset and length.
     */
    public MyMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <MyMsg> \n";
      try {
        s += "  [other=0x"+Long.toHexString(get_other())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [srcId=0x"+Long.toHexString(get_srcId())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [trgtId=0x"+Long.toHexString(get_trgtId())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data=";
        for (int i = 0; i < 10; i++) {
          s += "0x"+Long.toHexString(getElement_data(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: other
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'other' is signed (false).
     */
    public static boolean isSigned_other() {
        return false;
    }

    /**
     * Return whether the field 'other' is an array (false).
     */
    public static boolean isArray_other() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'other'
     */
    public static int offset_other() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'other'
     */
    public static int offsetBits_other() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'other'
     */
    public short get_other() {
        return (short)getUIntBEElement(offsetBits_other(), 8);
    }

    /**
     * Set the value of the field 'other'
     */
    public void set_other(short value) {
        setUIntBEElement(offsetBits_other(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'other'
     */
    public static int size_other() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'other'
     */
    public static int sizeBits_other() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: srcId
    //   Field type: short, unsigned
    //   Offset (bits): 8
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'srcId' is signed (false).
     */
    public static boolean isSigned_srcId() {
        return false;
    }

    /**
     * Return whether the field 'srcId' is an array (false).
     */
    public static boolean isArray_srcId() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'srcId'
     */
    public static int offset_srcId() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'srcId'
     */
    public static int offsetBits_srcId() {
        return 8;
    }

    /**
     * Return the value (as a short) of the field 'srcId'
     */
    public short get_srcId() {
        return (short)getUIntBEElement(offsetBits_srcId(), 8);
    }

    /**
     * Set the value of the field 'srcId'
     */
    public void set_srcId(short value) {
        setUIntBEElement(offsetBits_srcId(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'srcId'
     */
    public static int size_srcId() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'srcId'
     */
    public static int sizeBits_srcId() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: trgtId
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'trgtId' is signed (false).
     */
    public static boolean isSigned_trgtId() {
        return false;
    }

    /**
     * Return whether the field 'trgtId' is an array (false).
     */
    public static boolean isArray_trgtId() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'trgtId'
     */
    public static int offset_trgtId() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'trgtId'
     */
    public static int offsetBits_trgtId() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'trgtId'
     */
    public int get_trgtId() {
        return (int)getUIntBEElement(offsetBits_trgtId(), 16);
    }

    /**
     * Set the value of the field 'trgtId'
     */
    public void set_trgtId(int value) {
        setUIntBEElement(offsetBits_trgtId(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'trgtId'
     */
    public static int size_trgtId() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'trgtId'
     */
    public static int sizeBits_trgtId() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data
    //   Field type: int[], unsigned
    //   Offset (bits): 32
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data' is signed (false).
     */
    public static boolean isSigned_data() {
        return false;
    }

    /**
     * Return whether the field 'data' is an array (true).
     */
    public static boolean isArray_data() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'data'
     */
    public static int offset_data(int index1) {
        int offset = 32;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data'
     */
    public static int offsetBits_data(int index1) {
        int offset = 32;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'data' as a int[]
     */
    public int[] get_data() {
        int[] tmp = new int[10];
        for (int index0 = 0; index0 < numElements_data(0); index0++) {
            tmp[index0] = getElement_data(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'data' from the given int[]
     */
    public void set_data(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_data(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'data'
     */
    public int getElement_data(int index1) {
        return (int)getUIntBEElement(offsetBits_data(index1), 16);
    }

    /**
     * Set an element of the array 'data'
     */
    public void setElement_data(int index1, int value) {
        setUIntBEElement(offsetBits_data(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'data'
     */
    public static int totalSize_data() {
        return (160 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'data'
     */
    public static int totalSizeBits_data() {
        return 160;
    }

    /**
     * Return the size, in bytes, of each element of the array 'data'
     */
    public static int elementSize_data() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'data'
     */
    public static int elementSizeBits_data() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'data'
     */
    public static int numDimensions_data() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'data'
     */
    public static int numElements_data() {
        return 10;
    }

    /**
     * Return the number of elements in the array 'data'
     * for the given dimension.
     */
    public static int numElements_data(int dimension) {
      int array_dims[] = { 10,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
