#!/bin/bash
#!/bin/bash
# @author Aitor Hernandez
# @title moteSelfTriggered
# @modified 2011/06/01
#
# This script is specifically developed to program the motes for the 
# WaterTanks using the SelfTriggered controller.

# The core of the script is build is PHP. See motelistSelfTriggered.php
# for more details.

source ~/default-tinyos.sh /home/kthwsn/workspace/tinyos-2.x-svn

php /home/kthwsn/bin/motelistSelfTriggered.php $@ > motelist.m
