COMPONENT=ActuatorAppC
PFLAGS += -DIEEE154_BEACON_TX_DISABLED

CFLAGS += -I$(TOSDIR)/lib/printf
PFLAGS += -DPRINTF_BUFFER_SIZE=1000

CFLAGS += -I$(shell pwd)/..
CFLAGS += -I$(shell pwd)/../..

include ../Makefile.include