/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'SuperframeConfigMsg'
 * message type.
 */

public class SuperframeConfigMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 15;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 13;

    /** Create a new SuperframeConfigMsg of size 15. */
    public SuperframeConfigMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new SuperframeConfigMsg of the given data_length. */
    public SuperframeConfigMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SuperframeConfigMsg with the given data_length
     * and base offset.
     */
    public SuperframeConfigMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SuperframeConfigMsg using the given byte array
     * as backing store.
     */
    public SuperframeConfigMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SuperframeConfigMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public SuperframeConfigMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SuperframeConfigMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public SuperframeConfigMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SuperframeConfigMsg embedded in the given message
     * at the given base offset.
     */
    public SuperframeConfigMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SuperframeConfigMsg embedded in the given message
     * at the given base offset and length.
     */
    public SuperframeConfigMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <SuperframeConfigMsg> \n";
      try {
        s += "  [BI=0x"+Long.toHexString(get_BI())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [timeslots=";
        for (int i = 0; i < 10; i++) {
          s += "0x"+Long.toHexString(getElement_timeslots(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [ref="+Float.toString(get_ref())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: BI
    //   Field type: short
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'BI' is signed (true).
     */
    public static boolean isSigned_BI() {
        return true;
    }

    /**
     * Return whether the field 'BI' is an array (false).
     */
    public static boolean isArray_BI() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'BI'
     */
    public static int offset_BI() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'BI'
     */
    public static int offsetBits_BI() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'BI'
     */
    public short get_BI() {
        return (short)getUIntBEElement(offsetBits_BI(), 8);
    }

    /**
     * Set the value of the field 'BI'
     */
    public void set_BI(short value) {
        setUIntBEElement(offsetBits_BI(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'BI'
     */
    public static int size_BI() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'BI'
     */
    public static int sizeBits_BI() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: timeslots
    //   Field type: short[]
    //   Offset (bits): 8
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'timeslots' is signed (true).
     */
    public static boolean isSigned_timeslots() {
        return true;
    }

    /**
     * Return whether the field 'timeslots' is an array (true).
     */
    public static boolean isArray_timeslots() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'timeslots'
     */
    public static int offset_timeslots(int index1) {
        int offset = 8;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'timeslots'
     */
    public static int offsetBits_timeslots(int index1) {
        int offset = 8;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'timeslots' as a short[]
     */
    public short[] get_timeslots() {
        short[] tmp = new short[10];
        for (int index0 = 0; index0 < numElements_timeslots(0); index0++) {
            tmp[index0] = getElement_timeslots(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'timeslots' from the given short[]
     */
    public void set_timeslots(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_timeslots(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'timeslots'
     */
    public short getElement_timeslots(int index1) {
        return (short)getUIntBEElement(offsetBits_timeslots(index1), 8);
    }

    /**
     * Set an element of the array 'timeslots'
     */
    public void setElement_timeslots(int index1, short value) {
        setUIntBEElement(offsetBits_timeslots(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'timeslots'
     */
    public static int totalSize_timeslots() {
        return (80 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'timeslots'
     */
    public static int totalSizeBits_timeslots() {
        return 80;
    }

    /**
     * Return the size, in bytes, of each element of the array 'timeslots'
     */
    public static int elementSize_timeslots() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'timeslots'
     */
    public static int elementSizeBits_timeslots() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'timeslots'
     */
    public static int numDimensions_timeslots() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'timeslots'
     */
    public static int numElements_timeslots() {
        return 10;
    }

    /**
     * Return the number of elements in the array 'timeslots'
     * for the given dimension.
     */
    public static int numElements_timeslots(int dimension) {
      int array_dims[] = { 10,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'timeslots' with a String
     */
    public void setString_timeslots(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_timeslots(i, (short)s.charAt(i));
         }
         setElement_timeslots(i, (short)0); //null terminate
    }

    /**
     * Read the array 'timeslots' as a String
     */
    public String getString_timeslots() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,10)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_timeslots(i) == (char)0) break;
             carr[i] = (char)getElement_timeslots(i);
         }
         return new String(carr,0,i);
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: ref
    //   Field type: float
    //   Offset (bits): 88
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'ref' is signed (true).
     */
    public static boolean isSigned_ref() {
        return true;
    }

    /**
     * Return whether the field 'ref' is an array (false).
     */
    public static boolean isArray_ref() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'ref'
     */
    public static int offset_ref() {
        return (88 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'ref'
     */
    public static int offsetBits_ref() {
        return 88;
    }

    /**
     * Return the value (as a float) of the field 'ref'
     */
    public float get_ref() {
        return (float)getFloatElement(offsetBits_ref(), 32);
    }

    /**
     * Set the value of the field 'ref'
     */
    public void set_ref(float value) {
        setFloatElement(offsetBits_ref(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'ref'
     */
    public static int size_ref() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'ref'
     */
    public static int sizeBits_ref() {
        return 32;
    }

}
