COMPONENT=ControllerAppC
CFLAGS += -DWT_USERBUTTON
		CFLAGS += -DWT_USERBUTTON

CFLAGS += -I$(TOSDIR)/lib/printf
PFLAGS += -DPRINTF_BUFFER_SIZE=1000
CFLAGS += -I$(shell pwd)/..
CFLAGS += -I$(shell pwd)/../..

include ../Makefile.include