fprintf('Got Base Station \n');
motes.nMotes=3;
motes.moteList=cell(3,1);
motes.moteList{1}.reference='M49W90I1';
motes.moteList{1}.port=0;
motes.moteList{1}.id=0;
motes.moteList{1}.description='Moteiv tmote sky';
motes.moteList{2}.reference='MFT4LLHH';
motes.moteList{2}.port=2;
motes.moteList{2}.id=1;
motes.moteList{2}.description='FTDI MTM-CM5000MSP';
motes.moteList{3}.reference='MFT4LNK3';
motes.moteList{3}.port=3;
motes.moteList{3}.id=2;
motes.moteList{3}.description='FTDI MTM-CM5000MSP';
motes.baseStation='M49W90I1';
motes.sniffer='M49W90FU';
