/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'SensorMatrixMsg'
 * message type.
 */

public class SensorMatrixMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 32;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 12;

    /** Create a new SensorMatrixMsg of size 32. */
    public SensorMatrixMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new SensorMatrixMsg of the given data_length. */
    public SensorMatrixMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorMatrixMsg with the given data_length
     * and base offset.
     */
    public SensorMatrixMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorMatrixMsg using the given byte array
     * as backing store.
     */
    public SensorMatrixMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorMatrixMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public SensorMatrixMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorMatrixMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public SensorMatrixMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorMatrixMsg embedded in the given message
     * at the given base offset.
     */
    public SensorMatrixMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorMatrixMsg embedded in the given message
     * at the given base offset and length.
     */
    public SensorMatrixMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <SensorMatrixMsg> \n";
      try {
        s += "  [tankLevel1=";
        for (int i = 0; i < 8; i++) {
          s += "0x"+Long.toHexString(getElement_tankLevel1(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [tankLevel2=";
        for (int i = 0; i < 8; i++) {
          s += "0x"+Long.toHexString(getElement_tankLevel2(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: tankLevel1
    //   Field type: int[], unsigned
    //   Offset (bits): 0
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'tankLevel1' is signed (false).
     */
    public static boolean isSigned_tankLevel1() {
        return false;
    }

    /**
     * Return whether the field 'tankLevel1' is an array (true).
     */
    public static boolean isArray_tankLevel1() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'tankLevel1'
     */
    public static int offset_tankLevel1(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 8) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'tankLevel1'
     */
    public static int offsetBits_tankLevel1(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 8) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'tankLevel1' as a int[]
     */
    public int[] get_tankLevel1() {
        int[] tmp = new int[8];
        for (int index0 = 0; index0 < numElements_tankLevel1(0); index0++) {
            tmp[index0] = getElement_tankLevel1(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'tankLevel1' from the given int[]
     */
    public void set_tankLevel1(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_tankLevel1(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'tankLevel1'
     */
    public int getElement_tankLevel1(int index1) {
        return (int)getUIntBEElement(offsetBits_tankLevel1(index1), 16);
    }

    /**
     * Set an element of the array 'tankLevel1'
     */
    public void setElement_tankLevel1(int index1, int value) {
        setUIntBEElement(offsetBits_tankLevel1(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'tankLevel1'
     */
    public static int totalSize_tankLevel1() {
        return (128 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'tankLevel1'
     */
    public static int totalSizeBits_tankLevel1() {
        return 128;
    }

    /**
     * Return the size, in bytes, of each element of the array 'tankLevel1'
     */
    public static int elementSize_tankLevel1() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'tankLevel1'
     */
    public static int elementSizeBits_tankLevel1() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'tankLevel1'
     */
    public static int numDimensions_tankLevel1() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'tankLevel1'
     */
    public static int numElements_tankLevel1() {
        return 8;
    }

    /**
     * Return the number of elements in the array 'tankLevel1'
     * for the given dimension.
     */
    public static int numElements_tankLevel1(int dimension) {
      int array_dims[] = { 8,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: tankLevel2
    //   Field type: int[], unsigned
    //   Offset (bits): 128
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'tankLevel2' is signed (false).
     */
    public static boolean isSigned_tankLevel2() {
        return false;
    }

    /**
     * Return whether the field 'tankLevel2' is an array (true).
     */
    public static boolean isArray_tankLevel2() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'tankLevel2'
     */
    public static int offset_tankLevel2(int index1) {
        int offset = 128;
        if (index1 < 0 || index1 >= 8) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'tankLevel2'
     */
    public static int offsetBits_tankLevel2(int index1) {
        int offset = 128;
        if (index1 < 0 || index1 >= 8) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'tankLevel2' as a int[]
     */
    public int[] get_tankLevel2() {
        int[] tmp = new int[8];
        for (int index0 = 0; index0 < numElements_tankLevel2(0); index0++) {
            tmp[index0] = getElement_tankLevel2(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'tankLevel2' from the given int[]
     */
    public void set_tankLevel2(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_tankLevel2(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'tankLevel2'
     */
    public int getElement_tankLevel2(int index1) {
        return (int)getUIntBEElement(offsetBits_tankLevel2(index1), 16);
    }

    /**
     * Set an element of the array 'tankLevel2'
     */
    public void setElement_tankLevel2(int index1, int value) {
        setUIntBEElement(offsetBits_tankLevel2(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'tankLevel2'
     */
    public static int totalSize_tankLevel2() {
        return (128 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'tankLevel2'
     */
    public static int totalSizeBits_tankLevel2() {
        return 128;
    }

    /**
     * Return the size, in bytes, of each element of the array 'tankLevel2'
     */
    public static int elementSize_tankLevel2() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'tankLevel2'
     */
    public static int elementSizeBits_tankLevel2() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'tankLevel2'
     */
    public static int numDimensions_tankLevel2() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'tankLevel2'
     */
    public static int numElements_tankLevel2() {
        return 8;
    }

    /**
     * Return the number of elements in the array 'tankLevel2'
     * for the given dimension.
     */
    public static int numElements_tankLevel2(int dimension) {
      int array_dims[] = { 8,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
