#!/bin/bash
# @author Aitor Hernandez
# @title motereinstall
# @modified 2011/06/01
#
# Script to compile and install automatically the desired application in
# the nodes that are specified as arguments. 


# check the arguments
EXPECTED_ARGS=3
if [ $# -lt $EXPECTED_ARGS ]
then
	echo "Usage: moteallClass <app name> {<port name /dev/ttyUSBX> <id>}"
	exit -1
fi
# go to the desired application
cd $1
shift
echo "######################### PROGRAMMING THE $1 MOTES"
shift

# compile the application and exit the program if there is any error
make tmote &> errorFile
if [ $? != 0 ] ; then
	cat errorFile
	rm errorFile
	exit
fi
	echo "                 [OK]"

# program the app to all the nodes with the port and id specified
n_args=$#
let "n_args /= 2"
for i in $(seq $n_args)
do
	make tmote reinstall,$1 bsl,$2 &
shift
shift
done

exit
