/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'TestSerialCommMsg'
 * message type.
 */

public class TestSerialCommMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 4;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 6;

    /** Create a new TestSerialCommMsg of size 4. */
    public TestSerialCommMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new TestSerialCommMsg of the given data_length. */
    public TestSerialCommMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialCommMsg with the given data_length
     * and base offset.
     */
    public TestSerialCommMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialCommMsg using the given byte array
     * as backing store.
     */
    public TestSerialCommMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialCommMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public TestSerialCommMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialCommMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public TestSerialCommMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialCommMsg embedded in the given message
     * at the given base offset.
     */
    public TestSerialCommMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialCommMsg embedded in the given message
     * at the given base offset and length.
     */
    public TestSerialCommMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <TestSerialCommMsg> \n";
      try {
        s += "  [dummy=0x"+Long.toHexString(get_dummy())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [counter=0x"+Long.toHexString(get_counter())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: dummy
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'dummy' is signed (false).
     */
    public static boolean isSigned_dummy() {
        return false;
    }

    /**
     * Return whether the field 'dummy' is an array (false).
     */
    public static boolean isArray_dummy() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'dummy'
     */
    public static int offset_dummy() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'dummy'
     */
    public static int offsetBits_dummy() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'dummy'
     */
    public int get_dummy() {
        return (int)getUIntBEElement(offsetBits_dummy(), 16);
    }

    /**
     * Set the value of the field 'dummy'
     */
    public void set_dummy(int value) {
        setUIntBEElement(offsetBits_dummy(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'dummy'
     */
    public static int size_dummy() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'dummy'
     */
    public static int sizeBits_dummy() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: counter
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'counter' is signed (false).
     */
    public static boolean isSigned_counter() {
        return false;
    }

    /**
     * Return whether the field 'counter' is an array (false).
     */
    public static boolean isArray_counter() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'counter'
     */
    public static int offset_counter() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'counter'
     */
    public static int offsetBits_counter() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'counter'
     */
    public int get_counter() {
        return (int)getUIntBEElement(offsetBits_counter(), 16);
    }

    /**
     * Set the value of the field 'counter'
     */
    public void set_counter(int value) {
        setUIntBEElement(offsetBits_counter(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'counter'
     */
    public static int size_counter() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'counter'
     */
    public static int sizeBits_counter() {
        return 16;
    }

}
