COMPONENT=ActuatorAppC
PFLAGS += -DIEEE154_GTS_DISABLED \
		  -DIEEE154_BEACON_TX_DISABLED \
		  -DTKN154_BEACON_DISABLED 


CFLAGS += -I$(shell pwd)/../../../..
CFLAGS += -I$(shell pwd)/../../..
CFLAGS += -I$(shell pwd)/../..
CFLAGS += -I$(shell pwd)/..

include ../../../../Makefile.include