
#ifndef __APP_PROFILE_H
#define __APP_PROFILE_H

enum {
  RADIO_CHANNEL = 25,
  PAN_ID = 0x1234,
  //BASE_NODEID=10,
  //INTERMEDIATE_NODEID=11,
  INTERMEDIATE_NODEID=0x00,
  COORDINATOR_ADDRESS = INTERMEDIATE_NODEID,
  BASE_NODEID = COORDINATOR_ADDRESS,
  BEACON_ORDER = 6,
  SUPERFRAME_ORDER = 6,
  TX_POWER = 0, // in dBm

  //BUFFER_SIZE=10,
  BUFFER_SIZE=1, 
  FIRST_PLUG=1,
  SECOND_PLUG=2,

};
#endif
