COMPONENT=TestGtsAppC
CFLAGS += -I$(TOSDIR)/lib/printf 
CFLAGS += -I$(shell pwd)/..  
#PFLAGS += -DPRINTF_BUFFER_SIZE=1000 #-DTKN154_STD_DEALLOCATION


include $(TOSCONTRIB)/kth/tkn154-gts/apps/Makefile.include

#include $(MAKERULES)
